import type { PersonalRecord } from "@prisma/client";

const records: PersonalRecord[] = [
  {
    id: "",
    shouldDisplayOnProile: true,
    displayOrder: 4,
    sports: ["柔道"],
    recordCompetition: "judo",
    recordCategory: "eventResult",
    recordCategoryDetail: "judoResult",
    recordTarget: "rank",
    displayType: "myChoice",
    eventId: "第72回 東京都中学校対抗柔道大会",
    recordDatetime: "2023/07/28",
    recordValue: "4位",
    sharing: "followers",
    likeCount: 10,
    commentCount: 4,
  },
  {
    id: "",
    shouldDisplayOnProile: false,
    sports: ["バレーボール"],
    teamId: "わいわいず",
    recordCompetition: "volleyball",
    recordCategory: "eventResult",
    recordCategoryDetail: "volleyballTeamResult",
    recordTarget: "rank",
    displayType: "myChoice",
    recordValue: "第28回 わいわいカップ",
    recordDatetime: "2023/07/28",
    content: "優勝",
    sharing: "followers",
    likeCount: 10,
    commentCount: 4,
  },
  {
    id: "",
    shouldDisplayOnProile: false,
    sports: null,
    recordCategory: "bodyMeasurement",
    recordCategoryDetail: "bodyWeightMeasurement",
    recordTarget: "weight",
    displayType: "latestPersonalRecord",
    recordValue: "44kg",
    recordDatetime: "2024/03/14 10:00:00",
    sharing: "private",
    content: "ファスティング 3日目",
    likeCount: 10,
    commentCount: 4,
  },
  {
    id: "",
    shouldDisplayOnProile: false,
    sports: null,
    recordCategory: "bodyMeasurement",
    recordCategoryDetail: "bodyFatMeasurement",
    recordTarget: "bodyFat",
    displayType: "latestPersonalRecord",
    sharing: "private",
    recordDatetime: "2024/03/14 10:00:00",
    recordValue: "21.5%",
    property: "ファスティング 3日目",
    content: "",
    likeCount: null,
    commentCount: 2,
  },
  {
    id: "",
    shouldDisplayOnProile: false,
    sports: null,
    recordCategory: "bodyMeasurement",
    recordCategoryDetail: "bodyWeightMeasurement",
    recordTarget: "weight",
    recordValue: "45.4kg",
    recordDatetime: "2024/03/13 9:00:00",
    sharing: "private",
    content: "ファスティング 2日目",
    likeCount: 10,
    commentCount: 4,
  },
  {
    id: "",
    shouldDisplayOnProile: false,
    sports: null,
    recordCategory: "bodyMeasurement",
    recordCategoryDetail: "bodyFatMeasurement",
    recordTarget: "bodyFat",
    sharing: "private",
    recordDatetime: "2024/03/13 9:00:00",
    recordValue: "20.5%",
    property: "ファスティング 2日目",
    content: "",
    likeCount: null,
    commentCount: 2,
  },
  {
    id: "",
    shouldDisplayOnProile: false,
    sports: null,
    recordCategory: "bodyMeasurement",
    recordCategoryDetail: "bodyWeightMeasurement",
    recordTarget: "weight",
    recordValue: "45.9kg",
    recordDatetime: "2024/03/12 11:00:00",
    sharing: "private",
    content: "ファスティング 1日目",
    likeCount: 10,
    commentCount: 4,
  },
  {
    id: "",
    shouldDisplayOnProile: false,
    sports: null,
    recordCategory: "bodyMeasurement",
    recordCategoryDetail: "bodyFatMeasurement",
    recordTarget: "bodyFat",
    sharing: "private",
    recordDatetime: "2024/03/12 11:00:00",
    recordValue: "21%",
    property: "ファスティング 1日目",
    content: "",
    likeCount: null,
    commentCount: 2,
  },
  {
    id: "",
    shouldDisplayOnProile: true,
    displayOrder: 1,
    sports: ["陸上"],
    recordCompetition: "100mSprint",
    recordCategory: "highlight",
    recordCategoryDetail: "100mSprintVideoHighlight",
    recordTarget: "video",
    displayType: "myChoice",
    recordDatetime: "2023/12/31 18:00:00",
    recordValue: "私のベストプレー集2023",
    mediaUrl: "/dummy/images/bestplayvideo.webp",
    likeCount: 10000,
    commentCount: 128,
  },
  {
    id: "",
    shouldDisplayOnProile: true,
    displayOrder: 3,
    sports: ["陸上", "陸上100m"],
    recordCompetition: "100mSprint",
    recordCategory: "eventResult",
    recordCategoryDetail: "100mSprintResult",
    recordTarget: ["time", "rank"],
    displayType: "personalBestRecord",
    eventId: "2023 東京都高校陸上大会",
    recordValue: "11.21秒 2位",
    recordDatetime: "2022/04/28",
    content: "嬉しい。ようやく11.2秒台",
    likeCount: 10,
    commentCount: 4,
  },

  {
    id: "",
    shouldDisplayOnProile: false,
    sports: ["陸上", "陸上100m"],
    recordCompetition: "100mSprint",
    recordCategory: "eventResult",
    recordCategoryDetail: "100mSprintResult",
    recordTarget: ["time", "rank"],
    eventId: "2022 東京都高校陸上大会",
    recordValue: "11.7秒 5位",
    recordDatetime: "2022/04/28",
    content: "",
    likeCount: 10,
    commentCount: 4,
  },
  {
    id: "",
    shouldDisplayOnProile: false,
    sports: ["陸上", "陸上100m"],
    recordCompetition: "100mSprint",
    recordCategory: "activityResult",
    recordCategoryDetail: "100mSprintResult",
    recordTarget: ["time"],
    activityId: "とある日の練習2",
    recordValue: "11.8秒",
    recordDatetime: "2022/03/21",
    content: "新記録!! 非公式だけど）",
    likeCount: 10,
    commentCount: 4,
  },
  {
    id: "",
    shouldDisplayOnProile: false,
    sports: ["陸上", "陸上100m"],
    recordCompetition: "100mSprint",
    recordCategory: "activityResult",
    recordCategoryDetail: "100mSprintResult",
    recordTarget: ["time"],
    activityId: "とある日の練習1",
    recordValue: "11.9秒",
    recordDatetime: "2022/01/28",
    likeCount: 10,
    commentCount: 4,
  },
  {
    id: "",
    shouldDisplayOnProile: true,
    displayOrder: 2,
    sports: ["陸上", "longDistance"],
    recordCompetition: "halfMarathon",
    recordCategory: "eventResult",
    recordCategoryDetail: "halfMarathonResult",
    recordTarget: ["time"],
    displayType: "personalLatestRecord",
    eventId: "熊本マラソン2024",
    recordValue: "5:50:22",
    recordDatetime: "2024.02.22",
    likeCount: 10,
    commentCount: 4,
  },
  {
    id: "",
    shouldDisplayOnProile: false,
    sports: ["陸上", "longDistance"],
    recordCompetition: "halfMarathon",
    recordCategory: "eventResult",
    recordCategoryDetail: "halfMarathonResult",
    recordTarget: ["time", "rank"],
    eventId: "熊本マラソン2023",
    recordValue: ["6:50:22", "6405位"],
    recordDatetime: "2023.02.22",
    likeCount: 12,
    commentCount: 4,
  },
  {
    id: "",
    shouldDisplayOnProile: true,
    displayOrder: 5,
    sports: ["陸上", "longDistance"],
    recordCompetition: "halfMarathon",
    recordCategory: "eventResult",
    recordCategoryDetail: "halfMarathonResult",
    recordTarget: ["time", "rank"],
    displayType: "personalBestRecord",
    eventId: "東京マラソン2024",
    recordValue: ["4:40:22", "2800位"],
    recordDatetime: "2024.02.22",
    likeCount: 12,
    commentCount: 4,
  },
  {
    id: "",
    shouldDisplayOnProile: false,
    sports: ["陸上", "longDistance"],
    recordCompetition: "halfMarathon",
    recordCategory: "eventResult",
    recordCategoryDetail: "halfMarathonResult",
    recordTarget: ["time", "rank"],
    eventId: "熊本マラソン2022",
    recordValue: ["4:50:22", "2048位"],
    recordDatetime: "2023.02.22",
    likeCount: 12,
    commentCount: 4,
  },
].map((r, indx) => {
  r.id = `rid-${indx}`;
  return r;
});

export default {
  RECORDS: records,
  RECORDS_TO_DISPLAY: records
    .filter((r) => r.shouldDisplayOnProile)
    .sort((a, b) => ((a?.displayOrder || 0) > (b?.displayOrder || 0) ? 1 : -1)),
};
